<a href="https://colab.research.google.com/github/SurbhiOfficial/MachineLearningwithPython/blob/main/Surbhi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 Importing Libraries into Project 
 

In [ ]:
import numpy as np
import pandas as pd


Loading the Dataset 

In [ ]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

From Printing the keys of Iris_dataset 

In [ ]:
print("Keys of iris_dataset : \n {}".format(iris_dataset.keys()))

Keys of iris_dataset : 
 dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


Printing the Value of Description key of Iris_dataset

In [ ]:
print(iris_dataset['DESCR'][:194]+"\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pred
...


Printing the Value of Target_name key of Iris_dataset 

In [ ]:
print("Target names: {}".format(iris_dataset['target_names']))

Target names: ['setosa' 'versicolor' 'virginica']


Printing the Value of Feature Key of Iris_dataset 

In [ ]:
print("Feature Names: \n {}".format(iris_dataset['feature_names']))

Feature Names: 
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Printing the value of data key of Iris_dataset 

In [ ]:
print("Type of Data: \n {}".format(type(iris_dataset['data'])))

Type of Data: 
 <class 'numpy.ndarray'>


Printing the Shape of Data 

In [ ]:
print("Shape of data : {}".format(iris_dataset['data'].shape))

Shape of data : (150, 4)


Printing first 10 Columns of the data 

In [ ]:
print("First 10 Columns of the data : \n {}".format(iris_dataset['data'][:10]))

First 10 Columns of the data : 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


Printing the Type of Target key of iris_dataset 

In [ ]:
print("Type of Target : \n {}".format(type(iris_dataset['target'])))

Type of Target : 
 <class 'numpy.ndarray'>


Printing the Shape of Target key of Iris_dataset

In [ ]:
print("Shape of the Target key : \n {}".format(iris_dataset['target'].shape))

Shape of the Target key : 
 (150,)


Printing the Value of Target key of Iris_dataset 

In [ ]:
print("Value of target : \n {} ".format(iris_dataset['target']))

Value of target : 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2] 


Importing Train_test_split


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
  iris_dataset['data'], iris_dataset['target'], random_state=0)

Printing the Shape of X_train, X_test, y_train, y_test

In [ ]:
print("shape of X_train: {}".format(X_train.shape))
print("shape of X_test: {}".format(X_test.shape))
print("shape of y_train: {}".format(y_train.shape))
print("shape of y_test: {}".format(y_test.shape))

shape of X_train: (112, 4)
shape of X_test: (38, 4)
shape of y_train: (112,)
shape of y_test: (38,)


Importing KNeighborsClassifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

Training the Classifier

In [ ]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

Testing the Model on One Data point 

In [ ]:
x_new = np.array([[8,1.9,4,0.4]])
print("X_new.shape: {}".format(x_new.shape))
predication = knn.predict(x_new)
print("Prediction: {}".format(predication))
print("Predicted Target name: {}".format(
iris_dataset['target_names'][predication]))

X_new.shape: (1, 4)
Prediction: [1]
Predicated Target name: ['versicolor']


Test Set Prediction

In [ ]:
y_pred = knn.predict(X_test)
print("Test Set Predictions: \n {}".format(y_pred))

Test Set Predictions: 
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [ ]:
print("Test Set Score: {}".format(np.mean(y_pred  ==y_test)))

Test Set Score: 0.9736842105263158
